name: Sync Package to Main When release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
jobs:
  Sync_package_to_main:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}
    steps:
      - name: Apt Update
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install git

      - name: Clone OpenClash Repository
        uses: actions/checkout@v4
        with:
          ref: package

      - name: New Version
        id: current_version
        run: |
          echo "version=$(sed -n 1p ./${{ github.ref_name }}/version |awk -F '-' '{print $1}' |awk -F 'v' '{print $2}')" >> $GITHUB_OUTPUT
          echo "Current Version: $(sed -n 1p ./${{ github.ref_name }}/version |awk -F '-' '{print $1}' |awk -F 'v' '{print $2}')"

      - name: Sync dev package to main
        id: sync
        run: |
          if [ -n "$(diff -r ./main/ ./dev/)" ]; then
            rm -rf ./main/README.md
            rm -rf ./main/luci-app-rakitanmanager_*.ipk
            rm -rf ./main/version
            rm -rf ./main/changelog.txt
            cp -rf "./dev/." "./main/"
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Release: Auto sync dev package"
            git push
            echo "status=true" >> $GITHUB_OUTPUT
          else
            echo "status=false" >> $GITHUB_OUTPUT
            echo "main package already sync to dev, exit"
          fi

      - name: Generate new tag & release
        if: steps.sync.outputs.status == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          tag_name: "v${{ steps.current_version.outputs.version }}-beta"
          body: |
            ## :mega:Update content
            ---
            INSTALL & UPGRADE
            ---
            1. Buka / Akses Terminal Openwrt
            2. Jalankan Perintah ini di Terminal
            ```
            bash -c "$(wget -qO - 'https://raw.githubusercontent.com/rtaserver/rakitanmanager/main/install.sh')"
            ```